export const DOWJONES = [
    { "ticker": "AAPL", "company": "Apple Inc." },
    { "ticker": "AMGN", "company": "Amgen Inc." },
    { "ticker": "AMZN", "company": "Amazon.com, Inc." },
    { "ticker": "AXP", "company": "American Express Company" },
    { "ticker": "BA", "company": "Boeing Co." },
    { "ticker": "CAT", "company": "Caterpillar Inc." },
    { "ticker": "CRM", "company": "Salesforce, Inc." },
    { "ticker": "CSCO", "company": "Cisco Systems, Inc." },
    { "ticker": "CVX", "company": "Chevron Corporation" },
    { "ticker": "DIS", "company": "Walt Disney Company" },
    { "ticker": "DOW", "company": "Dow Inc." },
    { "ticker": "GS", "company": "Goldman Sachs Group, Inc." },
    { "ticker": "HD", "company": "Home Depot, Inc." },
    { "ticker": "HON", "company": "Honeywell International Inc." },
    { "ticker": "IBM", "company": "International Business Machines Corp." },
    { "ticker": "INTC", "company": "Intel Corporation" },
    { "ticker": "JNJ", "company": "Johnson & Johnson" },
    { "ticker": "JPM", "company": "JPMorgan Chase & Co." },
    { "ticker": "KO", "company": "Coca-Cola Company" },
    { "ticker": "MCD", "company": "McDonald's Corporation" },
    { "ticker": "MMM", "company": "3M Company" },
    { "ticker": "MRK", "company": "Merck & Co., Inc." },
    { "ticker": "MSFT", "company": "Microsoft Corporation" },
    { "ticker": "NKE", "company": "Nike, Inc." },
    { "ticker": "NVDA", "company": "Nvidia Corporation" },
    { "ticker": "PG", "company": "Procter & Gamble Company" },
    { "ticker": "SHW", "company": "Sherwin-Williams Company" },
    { "ticker": "TRV", "company": "Travelers Companies, Inc." },
    { "ticker": "UNH", "company": "UnitedHealth Group Incorporated" },
    { "ticker": "V", "company": "Visa Inc." },
    { "ticker": "VZ", "company": "Verizon Communications Inc." },
    { "ticker": "WMT", "company": "Walmart Inc." }
]
